//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JoePitt.Cards.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>UK (1.6)_dd12fa05-a7a7-4f6c-8467-4711abbcb16b</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection CardSets {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CardSets"]));
            }
            set {
                this["CardSets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Rounds {
            get {
                return ((int)(this["Rounds"]));
            }
            set {
                this["Rounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Cards {
            get {
                return ((int)(this["Cards"]));
            }
            set {
                this["Cards"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RandoCanlrissian {
            get {
                return ((bool)(this["RandoCanlrissian"]));
            }
            set {
                this["RandoCanlrissian"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NeverHaveI {
            get {
                return ((bool)(this["NeverHaveI"]));
            }
            set {
                this["NeverHaveI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Rebooting {
            get {
                return ((bool)(this["Rebooting"]));
            }
            set {
                this["Rebooting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Cheats {
            get {
                return ((bool)(this["Cheats"]));
            }
            set {
                this["Cheats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Player 01</string>
  <string>Player 02</string>
  <string>Player 03</string>
  <string>Player 04</string>
  <string>Player 05</string>
  <string>Player 06</string>
  <string>Player 07</string>
  <string>Player 08</string>
  <string>Player 09</string>
  <string>Player 10</string>
  <string>Player 11</string>
  <string>Player 12</string>
  <string>Player 13</string>
  <string>Player 14</string>
  <string>Player 15</string>
  <string>Player 16</string>
  <string>Player 17</string>
  <string>Player 18</string>
  <string>Player 19</string>
  <string>Player 20</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Names {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Names"]));
            }
            set {
                this["Names"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int LocalPlayers {
            get {
                return ((int)(this["LocalPlayers"]));
            }
            set {
                this["LocalPlayers"] = value;
            }
        }
    }
}
